### ISSUE TITLE
I can't find the offset to fix touch problem 

### ISSUE THREAD

**Issue by Abdo99980** [NepMods/Aide-Imgui#5]
The touch Pointers is in wrong positions on screen when I add it to Among Us 
Screen Resolution (1080x2408)
Window Size(840x450)

https://github.com/NepMods/Aide-Imgui/assets/87795539/2cf5794c-838b-46f4-b5c9-278e2fd0a5af

[Aide-Imgui-master 50.zip](https://github.com/user-attachments/files/16040142/Aide-Imgui-master.50.zip)

**Comment by NepMods** [comment]
Set your graphics quality to max

**Comment by Abdo99980** [comment]
How

**Comment by Abdo99980** [comment]
My Phone is Vivo Y33s

**Comment by Abdo99980** [comment]
How to set graphics to max
